filter:
    excluded_paths: [node_modules/*, test/*, tests/*]

checks:
    javascript: true
    python: true

build:
    nodes:
        analysis:
            tests:
                override: [js-scrutinizer-run, py-scrutinizer-run]
        
        coverage:
            tests:
                override:
                    - command: echo "no test"
                      coverage:
                        file: backend/coverage/clover.xml
                        format: clover
                    - command: echo "no test"
                      coverage:
                        file: sim-soft/coverage.xml
                        format: clover
