
filter:
    excluded_paths: [node_modules/*, test/*, tests/*, sim-soft/*]

build:
  nodes:
    coverage:
      tests:
        override:
          - command: echo "Skipping tests"  # Detta kommando gör ingenting, vi kör inga tester
            coverage:
              file: 'coverage/lcov-report/lcov.info'  # Här anger du platsen för den redan genererade täckningsrapporten
              format: 'lcov'  # Formatet på rapporten (t.ex. lcov)


                # coverage:
                #     file: backend/coverage/lcov.info
                #     format: lcov

        # coverage:
        #     tests:
        #         override:
        #             - command: ./my-test-run
        #             coverage:
        #                 file: backend/coverage/lcov.info

                        # These formats are supported:
                        # clover, cobertura, jacoco, python-cc, ruby-cc, go-cc, lcov
                        # format: lcov
