
filter:
    excluded_paths: [node_modules/*, test/*, tests/*, sim-soft/*]

checks:
    javascript: true
    python: true

build:
    nodes:
        analysis:
            tests:
                override: [js-scrutinizer-run, py-scrutinizer-run]
        coverage:
            tests:
                override:
                - command: make test  # Detta kommando gör ingenting, vi kör inga tester
                    coverage:
                    file: 'backend/coverage/lcov.info'  # Här anger du platsen för den redan genererade täckningsrapporten
                    format: 'lcov'

                # coverage:
                #     file: backend/coverage/lcov.info
                #     format: lcov

        # coverage:
        #     tests:
        #         override:
        #             - command: ./my-test-run
        #             coverage:
        #                 file: backend/coverage/lcov.info

                        # These formats are supported:
                        # clover, cobertura, jacoco, python-cc, ruby-cc, go-cc, lcov
                        # format: lcov
