build:
    nodes:
        backend:
            environment:
                node: "18"
                NODE_ENV: "test"
            commands:
                - cd backend
                - npm install
                - npm run lint  # Endast körning av lint för kodkvalitetsanalys

filter:
    excluded_paths:
        - "node_modules/*"
        - "backend/node_modules/*"

checks:
    javascript:
        code-complexity: true
        duplication: true
        unused-variables: true
        unreachable-code: true

tools:
    eslint:
        config: backend/.eslintrc.json
