
filter:
    excluded_paths: [node_modules/*, test/*, tests/*, sim-soft/*]

checks:
    javascript: true
    python: true

build:
    nodes:
        analysis:
            tests:
                override: [js-scrutinizer-run, py-scrutinizer-run]
        coverage:
            tests:
                override:
                - command: ./run-my-tests
                    coverage:
                    file: backend/coverage/coverage.xml   # <- Set this to where we find the coverage data.
                                                #    The path is relative to the current directory.
                    format: clover

                # coverage:
                #     file: backend/coverage/lcov.info
                #     format: lcov

        # coverage:
        #     tests:
        #         override:
        #             - command: ./my-test-run
        #             coverage:
        #                 file: backend/coverage/lcov.info

                        # These formats are supported:
                        # clover, cobertura, jacoco, python-cc, ruby-cc, go-cc, lcov
                        # format: lcov
