build:
    nodes:
        backend:
            environment:
                node: "18"
                NODE_ENV: "test"
            commands:
                - cd backend
                - npm install
                - npm run lint  # Endast körning av lint för kodkvalitetsanalys

filter:
    excluded_paths:
        - "node_modules/*"
        - "backend/node_modules/*"

checks:
    javascript:
        code_rating: true  # Generell kvalitetsbedömning
        no_unused_vars: true  # Kontrollera oanvända variabler
        no_unreachable: true  # Kontrollera oåtkomlig kod
        duplicate_code: true  # Kontrollera kodduplication

tools:
    eslint:
        config: backend/.eslintrc.json