imports:
    - python

filter:
    excluded_paths: 
        - "**/__pycache__/*"
        - "sim-soft/venv/*"

build:
    image: default-bionic

    nodes:
        analysis:
            language: python
            python:
                version: "3.10"
            tests:
                override:
                    # Navigate to sim-soft folder
                    - cd sim-soft
                    
                    # Run Pylint for static analysis
                    - pylint src/ --rcfile=pylint.conf
                    
                    # Run unit tests with coverage
                    - coverage run -m unittest discover tests/
                    - coverage report -m
    tests:
        override:
            - command: "cd sim-soft && coverage run -m unittest discover tests/"
                coverage:
                    file: "sim-soft/coverage.xml"
                    format: "cobertura"
