
filter:
    excluded_paths: [node_modules/*, test/*, tests/*, frontend/*]

checks:
    javascript: true
    python: true

build:
    nodes:
        analysis:
            tests:
                override: [js-scrutinizer-run, py-scrutinizer-run]
