filter:
    excluded_paths: [node_modules/*, test/*, tests/*, sim-soft/*]

checks:
    javascript: true
    python: true

build:
    nodes:
        analysis:
            tests:
                override: [js-scrutinizer-run, py-scrutinizer-run]
        
        coverage:
            tests:
                override:
                  - command: echo "Skipping tests"
                    coverage:
                      file: backend/coverage/coverage.xml  # Ange rätt filväg till Clover-rapporten
                      format: clover  # Formatet är Clover (XML)
