
filter:
    excluded_paths: [node_modules/*, test/*, frontend/*]

checks:
    javascript: true
    python: true

build:
    nodes:
        analysis:
            tests:
                override:
                    - js-scrutinizer-run
                    - python-scrutinizer-run
