networks:
  bike_network:
    driver: bridge

volumes:
  mariadb_data:

services:
  database:
    image: mariadb:latest
    container_name: mariadb-compose
    environment:
      MYSQL_ROOT_PASSWORD: scrt_pa_s_db
      MYSQL_DATABASE: vteam
      MYSQL_USER: dbadm
      MYSQL_PASSWORD: scrt_pa_s_db
    ports:
      - "3306:3306"
    networks:
      - bike_network
    volumes:
      - mariadb_data:/var/lib/mysql
      - "./backend/database/zone.csv:/docker-entrypoint-initdb.d/zone.csv"
      - "./backend/database/setup.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./backend/database/ddl.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./backend/database/insert.sql:/docker-entrypoint-initdb.d/3.sql"
      # - "./backend/database/user.csv:/docker-entrypoint-initdb.d/user.csv"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    volumes:
      - ./backend:/backend
    ports:
      - "1337:1337"
    networks:
      - bike_network
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: dbadm
      DB_PASSWORD: scrt_pa_s_db
      DB_NAME: vteam
    restart: always

  simulation:
    build: ./sim-soft
    depends_on:
      - backend
    networks:
      - bike_network
    container_name: simulation
    volumes:
      - ./sim-soft/src:/app

  admin-web:
    build: ./frontend/admin-web
    depends_on:
      - backend
    container_name: admin-web-container
    volumes:
      - ./frontend/admin-web:/app
    ports:
      - 3000:3000
    networks:
      - bike_network

  user-web:
    build: ./frontend/user-web
    depends_on:
      - backend
    container_name: user-web-container
    volumes:
      - ./frontend/user-web:/app
    ports:
      - 3001:3001
    networks:
      - bike_network

  user-app:
    build: ./frontend/user-app
    depends_on:
      - backend
    container_name: user-app-container
    volumes:
      - ./frontend/user-app:/app
    ports:
      - 3002:3002
    networks:
      - bike_network
