services:
  backend:
    build: ./backend
    container_name: backend-container

  frontend:
    build: ./frontend
    container_name: frontend-container

  simulation:
    build: ./sim-soft
    networks:
      - app_network
    container_name: simulation
    volumes:
      - ./sim-soft/src:/app

networks:
  app_network:
    driver: bridge