services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    volumes:
      - ./backend:/backend
    ports:
      - "1337:1337"
    networks:
      - app_network
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: dbadm
      DB_PASSWORD: scrt_pa_s_db
      DB_NAME: vteam
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend-container

  simulation:
    build: ./sim-soft
    networks:
      - app_network
    container_name: simulation
    volumes:
      - ./sim-soft/src:/app

  database:
    image: mariadb:latest
    container_name: mariadb-compose
    environment:
      MYSQL_ROOT_PASSWORD: scrt_pa_s_db
      MYSQL_DATABASE: vteam
      MYSQL_USER: dbadm
      MYSQL_PASSWORD: scrt_pa_s_db
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
    - "./backend/database/setup.sql:/docker-entrypoint-initdb.d/1.sql"
    - "./backend/database/ddl.sql:/docker-entrypoint-initdb.d/2.sql"

networks:
  app_network:
    driver: bridge
