name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # - name: Install dependencies
      #   run: |
      #     cd backend
      #     npm install

      # - name: Run ESLint
      #   run: |
      #     npx eslint backend

      # - name: Run tests
      #   run: npm test

  test-simulation:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.13

        - name: Install dependencies
          run: |
            python -m venv venv
            source venv/bin/activate
            pip install -r sim-soft/requirements.txt

        - name: Install Pylint
          run: |
            source venv/bin/activate
            pip install pylint

        - name: Run Pylint
          run: |
            source venv/bin/activate
            pylint sim-soft/src sim-soft/tests

        - name: Run unittest
          run: |
            source venv/bin/activate
            cd sim-soft
            python -m unittest discover tests
