jobs:
  test:
    runs-on: ubuntu-latest

    services:
      database:
        image: mariadb:latest  # Du kan använda MariaDB eller MySQL beroende på din databas
        env:
          MYSQL_ROOT_PASSWORD: scrt_pa_s_db
          MYSQL_DATABASE: testdb  # Här anger du vilken databas som ska skapas
          MYSQL_USER: dbadm
          MYSQL_PASSWORD: scrt_pa_s_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --user=root --password=${MYSQL_ROOT_PASSWORD}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Wait for MySQL to start
        run: |
          # Vänta tills databasen är redo för att ta emot anslutningar
          until mysql -h 127.0.0.1 -u root -pscrt_pa_s_db -e "SELECT 1"; do
            echo "Waiting for database to start..."
            sleep 5
          done

      - name: Setup test database schema
        run: |
          cd backend
          mysql -h 127.0.0.1 -u root -pscrt_pa_s_db testdb < ./database/setupDev.sql

      - name: Run tests
        run: |
          cd backend
          npm test
