name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  # these can be added later i think
  # test-backend: # backend tests
  # test-frontend: # frontend tests

  test-simulation:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.13

        - name: Install dependencies
          run: |
            python -m venv venv
            source venv/bin/activate
            pip install -r sim-soft/requirements.txt
        
        - name: Install Pylint
          run: |
            source venv/bin/activate
            pip install pylint

        - name: Run Pylint
          run: |
            source venv/bin/activate
            pylint sim-soft/src

        - name: Run unittest
          run: |
            source venv/bin/activate
            cd sim-soft
            python -m unittest discover tests

        # - name: Run flake8
        #   run: |
        #     source venv/bin/activate
        #     pip install flake8
        #     flake8 sim-soft/src

        # - name: Build Docker image
        #   run: |
        #     docker build -t simulation-image sim-soft/

        # - name: Run container tests
        #   run: |
        #     docker run --rm simulation-image python -m unittest discover -s /app/src/tests

        # - name: Cleanup Docker
        #   if: always()
        #   run: |
        #     docker system prune -f