on:
  push:
    branches: [ "**" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: scrt_pa_s_db
          MYSQL_DATABASE: testdb
          MYSQL_USER: dbadm
          MYSQL_PASSWORD: scrt_pa_s_db
        options: --health-cmd="mysqladmin ping --host=localhost --user=root --password=scrt_pa_s_db" --health-timeout=30s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18   # Sätt versionen av Node.js

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Wait for MariaDB to be ready
        run: |
          echo "Waiting for MariaDB to be ready..."
          until mysql --protocol=tcp -h localhost -u dbadm -p$scrt_pa_s_db -e "SHOW DATABASES"; do
            echo "Waiting for MariaDB..."
            sleep 5
          done
        env:
          scrt_pa_s_db: ${{ secrets.MYSQL_PASSWORD }}

      - name: Set up database schema
        run: |
          echo "Setting up the database schema..."
          mysql --protocol=tcp -h localhost -u dbadm -p$scrt_pa_s_db testdb < backend/database/setupDev.sql
        env:
          scrt_pa_s_db: ${{ secrets.MYSQL_PASSWORD }}

      - name: Run tests
        run: |
          cd backend
          npm test
