name: Test Backend with Docker

on:
  push:
    branches: [ "**" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start test services
        run: |
          docker-compose -f docker-compose.test.yml up -d --build
          
      - name: Wait for database to be ready
        run: |
          docker-compose exec -T testdatabase bash -c "until mysqladmin ping -h localhost --silent; do echo waiting for database; sleep 1; done; echo database is ready"

      - name: Run backend tests
        run: |
          docker exec backend-container npm test

      - name: Tear down services
        if: always()
        run: docker-compose down
