name: Test Backend with Docker

on:
  push:
    branches: [ "**" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start test services
        run: |
          docker-compose -f docker-compose.test.yml up -d --build

      - name: test with container
        run: |
            docker exec backend bash -c "npm install && npm test"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install npm
        run: |
          cd backend
          npm install
      - name: Run backend tests
        run: |
          cd backend
          npm test

      - name: Tear down services
        if: always()
        run: docker-compose down
