on:
  push:
    branches: [ "**" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out koden
    - name: Check out code
      uses: actions/checkout@v3

    # 2. Ställ in Docker Compose
    - name: Set up Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d testdatabase backend

    # 3. Vänta på att backend-tjänsten ska vara redo
    - name: Wait for backend to be ready
      run: |
        until docker logs backend-container 2>&1 | grep -q "Server is running"; do
          echo "Waiting for backend to start..."
          sleep 2
        done

    # 4. Kör testerna
    - name: Run tests
      run: |
        docker exec backend-container npm test

    # 5. Stäng ned tjänsterna
    - name: Tear down
      if: always()
      run: |
        docker-compose -f docker-compose.yml down

          

