jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: scrt_pa_s_db
          MYSQL_DATABASE: testdb
          MYSQL_USER: dbadm
          MYSQL_PASSWORD: scrt_pa_s_db
        options: --health-cmd="mysqladmin ping --host=localhost --user=root --password=scrt_pa_s_db" --health-timeout=30s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run tests
        run: |
          cd backend
          npm test
