on:
  push:
    branches: [ "**" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and start test services
        run: |
          docker-compose build backend
          docker-compose -f "docker-compose.yml" up -d testdatabase backend

      - name: Run tests
        run: |
          docker-compose exec backend npm test

      - name: Shutdown services
        run: |
          docker-compose down