on:
  push:
    branches: [ "**" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build the backend image
        run: |
          docker build -t vteam-05-backend ./backend

      - name: Start test database
        run: |
          docker run -d --name mariadb-compose-test \
            -e MYSQL_ROOT_PASSWORD=scrt_pa_s_db \
            -e MYSQL_DATABASE=testdb \
            -e MYSQL_USER=dbadm \
            -e MYSQL_PASSWORD=scrt_pa_s_db \
            -p 3307:3306 \
            mariadb:latest

      - name: Run tests in backend
        run: |
          docker run --rm --name backend-test-container \
            --network host \
            -e DB_HOST=localhost \
            -e DB_PORT=3307 \
            -e DB_USER=dbadm \
            -e DB_PASSWORD=scrt_pa_s_db \
            -e DB_NAME=testdb \
            vteam-05-backend npm test

      - name: Shutdown services
        run: |
          docker stop mariadb-compose-test
          docker rm mariadb-compose-test

          

