on:
  push:
    branches: [ "**" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.5
        ports:
          - 3306:3306
        env:
          MARIADB_ROOT_PASSWORD: root_password
          MARIADB_DATABASE: testdb
          MARIADB_USER: test_user
          MARIADB_PASSWORD: test_password
        options: --health-cmd="mysqladmin ping --host=localhost --user=root --password=root_password" --health-timeout=30s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Set up the database schema
        run: |
          mysql -h 127.0.0.1 -u root -proot_password testdb < backend/database/setupDev.sql
          mysql -h 127.0.0.1 -u root -proot_password testdb < backend/database/resetDev.sql

      - name: Run tests
        run: |
          cd backend
          npm test
