name: Backend CI

on:
  push:
    branches: [ "**" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      #- name: Install dependencies
      #  run: |
      #    cd backend
      #    npm install

     # - name: Run ESLint
     #   run: |
     #     npx eslint backend

      - name: Run tests
        run: |
          cd backend
          npm test
