name: Simulation CI

on:
  push:
    branches: [ "**" ]
    paths:
      - 'sim-soft/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'sim-soft/**'

jobs:
  test-simulation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/sim-soft/src" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r sim-soft/requirements.txt

      - name: Install Pylint
        run: |
          source venv/bin/activate
          pip install pylint

      - name: Run Pylint
        continue-on-error: true
        run: |
          source venv/bin/activate
          pylint sim-soft/src sim-soft/tests

      - name: Install coverage
        run: |
          source venv/bin/activate
          pip install coverage

      - name: Run tests with coverage
        run: |
          source venv/bin/activate
          cd sim-soft
          coverage run -m unittest discover tests
          coverage xml -o coverage.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: sim-soft/coverage.xml
